import { promises as fs } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const pagesRoot = path.resolve(__dirname, '../../pages')
const siteDir = path.resolve(__dirname, '..')
const targetDir = path.join(siteDir, 'pages')

async function sync() {
  await fs.mkdir(targetDir, { recursive: true })

  const entries = await fs.readdir(pagesRoot, { withFileTypes: true })
  const htmlFiles = entries
    .filter((e) => e.isFile() && e.name.toLowerCase().endsWith('.html'))
    .map((e) => e.name)
    .sort()

  for (const file of htmlFiles) {
    const src = path.join(pagesRoot, file)
    const dest = path.join(targetDir, file)
    await fs.copyFile(src, dest)
  }

  // Clean up files that no longer exist in the source folder
  const existingTargets = await fs.readdir(targetDir)
  for (const file of existingTargets) {
    if (!htmlFiles.includes(file)) {
      await fs.unlink(path.join(targetDir, file))
    }
  }

  // Generate a static JS file with the list of logs at the site root.
  // This avoids needing server-side directory listing on hosts like IONOS.
  const dataFile = `// Auto-generated by scripts/sync-pages.js
// Do not edit manually.
const LOGS = ${JSON.stringify(htmlFiles, null, 2)};
`
  await fs.writeFile(path.join(siteDir, 'logs-data.js'), dataFile)

  console.log(`Synced ${htmlFiles.length} log file(s) to website-static/pages.`)
}

sync().catch((err) => {
  console.error('Failed to sync pages:', err)
  process.exit(1)
})
