import { promises as fs, existsSync } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const siteDir = path.resolve(__dirname, '..')

// The source pages folder is normally next to the website-static folder,
// but it may also be nested under a "main" subfolder or located at the
// process working directory on CI runners. Try the common locations.
function findPagesRoot() {
  const candidates = [
    path.resolve(siteDir, '../pages'),
    path.resolve(siteDir, '../main/pages'),
    path.resolve(process.cwd(), 'pages'),
    path.resolve(process.cwd(), 'main/pages'),
    path.resolve(siteDir, '../../pages'),
    path.resolve(siteDir, '../../main/pages'),
  ]
  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      console.log(`Using pages source: ${candidate}`)
      return candidate
    }
  }
  // Default to the local sibling location so the error message is predictable.
  return candidates[0]
}

const pagesRoot = findPagesRoot()
const targetDir = path.join(siteDir, 'pages')

async function sync() {
  if (!existsSync(pagesRoot)) {
    throw new Error(
      `Could not find the source pages folder. Looked at: ${pagesRoot}\n` +
        `Make sure the "pages/" directory is committed to the repository.`
    )
  }

  await fs.mkdir(targetDir, { recursive: true })

  const entries = await fs.readdir(pagesRoot, { withFileTypes: true })
  const htmlFiles = entries
    .filter((e) => e.isFile() && e.name.toLowerCase().endsWith('.html'))
    .map((e) => e.name)
    .sort()

  for (const file of htmlFiles) {
    const src = path.join(pagesRoot, file)
    const dest = path.join(targetDir, file)
    await fs.copyFile(src, dest)
  }

  // Clean up files that no longer exist in the source folder,
  // but never delete hidden config files like .htaccess.
  const existingTargets = await fs.readdir(targetDir)
  for (const file of existingTargets) {
    if (!htmlFiles.includes(file) && !file.startsWith('.')) {
      await fs.unlink(path.join(targetDir, file))
    }
  }

  // Generate a static JS file with the list of logs at the site root.
  // This avoids needing server-side directory listing on hosts like IONOS.
  const dataFile = `// Auto-generated by scripts/sync-pages.js
// Do not edit manually.
const LOGS = ${JSON.stringify(htmlFiles, null, 2)};
`
  await fs.writeFile(path.join(siteDir, 'logs-data.js'), dataFile)

  // Allow directory listing inside pages/ so individual log files can be served
  // even if the host does not set a default for subdirectories.
  await fs.writeFile(
    path.join(targetDir, '.htaccess'),
    'Options +Indexes\n'
  )

  console.log(`Synced ${htmlFiles.length} log file(s) to website-static/pages.`)
}

sync().catch((err) => {
  console.error('Failed to sync pages:', err)
  process.exit(1)
})
