import { promises as fs, existsSync } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(__dirname, '..')
const pagesDir = path.join(rootDir, 'pages')
const dataFile = path.join(rootDir, 'logs-data.js')

async function sync() {
  if (!existsSync(pagesDir)) {
    throw new Error(
      `Could not find the pages folder at ${pagesDir}.\n` +
        `Make sure the "pages/" directory is committed to the repository.`
    )
  }

  const entries = await fs.readdir(pagesDir, { withFileTypes: true })
  const htmlFiles = entries
    .filter((e) => e.isFile() && e.name.toLowerCase().endsWith('.html'))
    .map((e) => e.name)
    .sort()

  // Generate a static JS file with the list of logs at the site root.
  // This avoids needing server-side directory listing on static hosts.
  const fileContent = `// Auto-generated by scripts/sync-pages.js
// Do not edit manually.
const LOGS = ${JSON.stringify(htmlFiles, null, 2)};
`
  await fs.writeFile(dataFile, fileContent)

  // Allow directory listing inside pages/ so individual log files can be
  // accessed directly even if the host does not set a default for subdirectories.
  await fs.writeFile(
    path.join(pagesDir, '.htaccess'),
    'Options +Indexes\n'
  )

  console.log(`Synced ${htmlFiles.length} log file(s).`)
}

sync().catch((err) => {
  console.error('Failed to sync pages:', err)
  process.exit(1)
})
